spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_wallet_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: myVerySecretKeyThatIsAtLeast32CharactersLongForSecurity
  expiration: 900000

server:
  port: 8080

logging:
  level:
    com.digitalwallet: DEBUG
