spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/digitalwallet}
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: false
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast256BitsLongForJWTSecurity123456789}
  expiration: 86400000

logging:
  level:
    com.digitalwallet: INFO
